fix DMS, invoice number, confirm form
demasjidofficial/demasjid_core pull request #229
Opened 2022-08-23 22:31 UTC by adityarifa

mohon saran dan masukkannya

2022-08-24 01:28 UTC, pandigresik requested changes
change request

2022-08-24 01:28 UTC, pandigresik commented on app/Config/Routes.php
>  $routes->post('/api/update_paymentmethod_activation', '\App\Modules\Api\Controllers\PaymentMethods::updateActived');
ini kenapa gak dimasukkan dalam group route api yang diatasnya ?

2022-08-24 01:28 UTC, pandigresik commented on app/Controllers/CampaignsPageController.php
>          // get data of navigation menu
bisa dihapus

2022-08-24 01:28 UTC, pandigresik commented on app/Controllers/ConfirmationofdonationController.php
> +    private function constructMenu($list) {
di file Checkoutcontroller juga ada function ini, mungkin bisa dijadikan satu di controller parent jika memungkinkan

2022-08-24 01:28 UTC, pandigresik commented on app/Controllers/Home.php
> +    private function constructMenu($list) {
di file Checkoutcontroller juga ada function ini, mungkin bisa dijadikan satu di controller parent jika memungkinkan

2022-08-24 01:28 UTC, pandigresik commented on app/Controllers/InformatonofpaymentController.php
> +    private function constructMenu($list) {
di file Checkoutcontroller juga ada function ini, mungkin bisa dijadikan satu di controller parent jika memungkinkan

2022-08-24 01:28 UTC, pandigresik commented on app/Modules/Api/Controllers/Donasis.php
> +        $INFO_SUCCESS = 'SUKSES KONFIRMASI';
mungkin bisa diganti dengan constanta

2022-08-24 22:23 UTC, adityarifa commented on app/Config/Routes.php
>  $routes->post('/api/update_paymentmethod_activation', '\App\Modules\Api\Controllers\PaymentMethods::updateActived');
maaf mas ini maksudnya bagaimana nggih?
atau bisa dicontohkan

2022-08-24 22:24 UTC, adityarifa commented on app/Controllers/CampaignsPageController.php
>          // get data of navigation menu
sudah di next commit

2022-08-24 22:29 UTC, adityarifa commented on app/Controllers/ConfirmationofdonationController.php
> +    private function constructMenu($list) {
siap, sudah di BaseController di next commit

2022-08-24 22:32 UTC, adityarifa commented on app/Modules/Api/Controllers/Donasis.php
> +        $INFO_SUCCESS = 'SUKSES KONFIRMASI';
dinaikkan ke bagian atas ya mas?

2022-08-26 00:57 UTC, pandigresik commented on app/Config/Routes.php
>  $routes->post('/api/update_paymentmethod_activation', '\App\Modules\Api\Controllers\PaymentMethods::updateActived');
sesuai percakapan via whatsapp kemarin

2022-08-26 01:03 UTC, pandigresik commented on app/Modules/Api/Controllers/Donasis.php
> +        $INFO_SUCCESS = 'SUKSES KONFIRMASI';
seperti ini 
https://github.com/demasjidofficial/demasjid_core/blob/develope/app/Modules/Api/Models/EntityModel.php

2022-08-30 17:08 UTC, adityarifa commented
no conflict mas, tp ada fungsi di donasiModel yang saya hapus utk resolve, setelah merge saya tambahkan lg. terima kasih

2022-08-31 01:11 UTC, merged