fix bug list
demasjidofficial/demasjid_core pull request #264
Opened 2022-09-15 14:11 UTC by adityarifa

2022-09-15 14:44 UTC, pandigresik requested changes

2022-09-15 14:44 UTC, pandigresik commented on app/Controllers/AdminCrudController.php
> +    protected $BLANK_IMG = 'assets/admin/images/blank.jpg';
umumnya huruf besar itu untuk constanta
bisa lihat file app/Modules/Api/Models/WilayahModel.php sebagai referensi. Jika bukan constanta pakai penamaan seperti lainnya saja $blankImg

2022-09-15 14:44 UTC, pandigresik commented on app/Modules/BaitulMal/Views/payment_method_paygat/_row_info.php
> +<td><img width="100px" src="/<?php echo ($item->master_paymentgateway_path_logo) ? esc($item->master_paymentgateway_path_logo   ) : $BLANK_IMG ?>"></a></td>
nama variabelnya kok huruf besar semua ($BLANK_IMG) ?

2022-09-15 14:44 UTC, pandigresik commented on app/Modules/Website/Module.php
> +            // 'permission'      => 'website.pages.list',
mengapa dimatikan pengecekan permissionnya ? termasuk baris yang dibawahnya juga

2022-09-15 14:44 UTC, pandigresik commented on app/Views/Campaign/confirm.php
> +                                    <img id="path_image_prev" src="<?php $blank_img ?>" alt="" class="img-thumbnail" style="height:200px">
src="<?php $blank_img ?>" akan menghasilkan string kosong, seharusnya ditambahkan echo sehingga menjadi <?php echo $blank_img ?> atau <?= $blank_img ?>

2022-09-21 01:19 UTC, adityarifa commented on app/Modules/Website/Module.php
> +            // 'permission'      => 'website.pages.list',
Itu kemarin di demo tdk muncul mas, karena tdk pakai user grup superadmin. Ini lebih baik ikutin yg sama apa dimunculkan utk userdemonya?

2022-09-21 01:29 UTC, adityarifa commented on app/Controllers/AdminCrudController.php
> +    protected $BLANK_IMG = 'assets/admin/images/blank.jpg';
Oke mas aku sesuaikan

2022-09-21 01:29 UTC, adityarifa commented on app/Controllers/AdminCrudController.php
> +    protected $BLANK_IMG = 'assets/admin/images/blank.jpg';
Itu constanta lokasi gambar sih mas

2022-09-21 01:29 UTC, adityarifa commented on app/Modules/BaitulMal/Views/payment_method_paygat/_row_info.php
> +<td><img width="100px" src="/<?php echo ($item->master_paymentgateway_path_logo) ? esc($item->master_paymentgateway_path_logo   ) : $BLANK_IMG ?>"></a></td>
Ikutin yg komen diatasnya mas

2022-09-21 05:08 UTC, pandigresik commented on app/Controllers/AdminCrudController.php
> +    protected $BLANK_IMG = 'assets/admin/images/blank.jpg';
kalau constanta seharusnya dideklarasikan seperti ini
const BLANK_IMG dan bisa diakses menggunakan self::BLANK_IMG
kalau variable biasa maka usahakan menggunakan penamaan seperti variabel lainnya

2022-09-21 05:10 UTC, pandigresik commented on app/Modules/Website/Module.php
> +            // 'permission'      => 'website.pages.list',
lebih baik tidak dimatikan, dan menambahkan hak aksesnya yang diperlukan ke usergroup yang dimaksud. Menambahkan hak akses website ke group superadmin

2022-10-02 21:48 UTC, adityarifa commented on app/Views/Campaign/confirm.php
> +                                    <img id="path_image_prev" src="<?php $blank_img ?>" alt="" class="img-thumbnail" style="height:200px">
di push berikutnya

2022-10-02 21:48 UTC, adityarifa commented on app/Modules/Website/Module.php
> +            // 'permission'      => 'website.pages.list',
di push berikutnya

2022-10-02 21:48 UTC, adityarifa commented on app/Modules/BaitulMal/Views/payment_method_paygat/_row_info.php
> +<td><img width="100px" src="/<?php echo ($item->master_paymentgateway_path_logo) ? esc($item->master_paymentgateway_path_logo   ) : $BLANK_IMG ?>"></a></td>
di push berikutnya

2022-10-02 21:48 UTC, adityarifa commented on app/Controllers/AdminCrudController.php
> +    protected $BLANK_IMG = 'assets/admin/images/blank.jpg';
di push berikutnya

2022-10-03 05:37 UTC, merged