Room aditya
demasjidofficial/demasjid_core pull request #266
Opened 2022-09-20 09:08 UTC by adityasoerya

Generate API fitur ROOM

2022-09-21 01:00 UTC, pandigresik requested changes

2022-09-21 01:00 UTC, pandigresik commented on app/Database/Migrations/2022-08-10-023234_Dataruangan.php
> +            'nama' => [
varchar gak perlu constraint unsigned

2022-09-21 01:00 UTC, pandigresik commented on app/Database/Migrations/2022-08-10-023234_Dataruangan.php
> +        $this->forge->createTable('dataruangan', true);
seperti tabel lainnya, jika 2 kata maka pisahkan dengan underscore menjadi data_ruangan, namun sepertinya lebih pas jika dinamakan ruangan begitu saja. Ini untuk master ruangan kan ?

2022-09-21 01:00 UTC, pandigresik commented on app/Database/Migrations/2022-08-18-074002_Room.php
> +            'deskripsi' => [
varchar gak perlu set unsigned menjadi false, cek juga di deklarasi kolom varchar lainnya

2022-09-21 01:00 UTC, pandigresik commented on app/Database/Migrations/2022-08-18-074002_Room.php
> +            'namaruangan' => [
cukup nama sebagai nama kolom

2022-09-21 01:00 UTC, pandigresik commented on app/Database/Migrations/2022-08-18-074002_Room.php
> +        $this->forge->createTable('room', true);
apa bedanya dengan tabel dataruangan diatas ?

2022-09-21 01:00 UTC, pandigresik commented on app/Database/Migrations/2022-08-29-023811_ComentRoom.php
> +            'saran' => [
saran seharusnya bisa lebih dari 50 karakter

2022-09-21 01:00 UTC, pandigresik commented on app/Database/Migrations/2022-08-29-023811_ComentRoom.php
> +            'kritik' => [
terlalu sedikit jika dibatasi 50 karakter

2022-09-21 01:00 UTC, pandigresik commented on app/Database/Migrations/2022-08-30-031117_RoomReserv.php
> +            'keterangan' => [
sepertinya bisa lebih 50 karakter

2022-09-21 01:00 UTC, pandigresik commented on app/Database/Migrations/2022-08-30-031117_RoomReserv.php
> +        $this->forge->createTable('room_reserv', true);
pakai nama tabel yang lengkap aja, room_reservation

2022-09-21 05:58 UTC, adityasoerya commented on app/Database/Migrations/2022-08-10-023234_Dataruangan.php
> +            'nama' => [
Sebenarnya saya tidak menggunakan Dataruangan.php , untuk master ruangan masuknya ke Room.php

2022-09-21 05:58 UTC, adityasoerya commented on app/Database/Migrations/2022-08-10-023234_Dataruangan.php
> +        $this->forge->createTable('dataruangan', true);
Sebenarnya saya tidak menggunakan Dataruangan.php , untuk master ruangan masuknya ke Room.php

2022-09-21 06:22 UTC, adityasoerya commented on app/Database/Migrations/2022-08-18-074002_Room.php
> +            'deskripsi' => [
Ketika saya ubah menjadi true terjadi eror, tetapi ketika saya hapus tidak terjadi eror.

2022-09-21 06:46 UTC, adityasoerya commented on app/Database/Migrations/2022-08-18-074002_Room.php
> +        $this->forge->createTable('room', true);
Sebenarnya saya tidak menggunakan tabel Dataruangan.php , untuk master ruangan masuknya ke tabel Room.php. Untuk Dataruangan itu branch sebelumnya dan saya sekarang saya menggunakan branch baru room_aditya yang master ruangan masuknya ke tabel Room.php

2022-09-22 00:25 UTC, pandigresik commented on app/Database/Migrations/2022-08-10-023234_Dataruangan.php
> +        $this->forge->createTable('dataruangan', true);
kalau memang sudah tidak dipakai, maka lebih baik dihapus saja deklarasi tabel tersebut dan semua file yang berhubungan dengan tabel tersebut

2022-10-07 22:31 UTC, merged