Board news devridho
demasjidofficial/demasjid_core pull request #268
Opened 2022-09-26 03:46 UTC by Muhammad-Ridho

2022-09-26 04:42 UTC, pandigresik requested changes

2022-09-26 04:42 UTC, pandigresik commented on app/Modules/Board/Views/board_news_bg/index.php
> +            <p><i>*untuk delay slideshow diatur secara default menjadi 5s</i></p>
kenapa diset statis 5 detik ? Sebelumnya mengikuti nilai dari variabel duration ?

2022-09-27 02:44 UTC, Muhammad-Ridho commented on app/Modules/Board/Views/board_news_bg/index.php
> +            <p><i>*untuk delay slideshow diatur secara default menjadi 5s</i></p>
menurut saya lebih baik diseragamkan untuk delay nya pak, menurut njenengan bagaimana pak?

2022-09-27 02:49 UTC, Muhammad-Ridho commented on app/Modules/Board/Views/board_news_bg/index.php
> +            <p><i>*untuk delay slideshow diatur secara default menjadi 5s</i></p>
untuk yang ini sudah saya perbaiki pak dan sudah tehubung database

2022-09-27 04:46 UTC, pandigresik commented on app/Modules/Board/Views/board_news_bg/index.php
> +            <p><i>*untuk delay slideshow diatur secara default menjadi 5s</i></p>
> menurut saya lebih baik diseragamkan untuk delay nya pak, menurut njenengan bagaimana pak?

agar bisa seragam bisa menggunakan nilai default jika mau, namun user tetap diberikan kebebasan untuk mengaturnya sehingga aplikasi akan menjadi sangat flexible bisa mengikuti kebutuhan user

2022-09-27 04:47 UTC, pandigresik approved these changes

2022-09-27 04:48 UTC, merged