Brain pendaftaran sisbaru devridho - Menu Pendaftaran
demasjidofficial/demasjid_core pull request #284
Opened 2022-10-13 13:07 UTC by Muhammad-Ridho

kurang pada view table bagian alamat masih dalam bentuk kode wilayah

2022-10-13 22:18 UTC, pandigresik requested changes
perbaiki dulu masalah struktur table ini, otomatis perubahan struktur table akan berimbas pada fitur CRUD juga

2022-10-13 22:18 UTC, pandigresik commented on app/Database/Migrations/2022-08-16-031332_CreatePesantrenMastereducationlevel.php
> +        $this->forge->createTable('pstr_educationlevel', true);
ini memang spesifik untuk kebutuhan pesantren sajakah ?
mungkin lebih baik penamaannya tidak menggunakan singkatan pesantren_educationlevel. Jika memungkinkan akan lebih baik dibuat general sehingga tabelnya menjadi education_level

2022-10-13 22:18 UTC, pandigresik commented on app/Database/Migrations/2022-08-16-044643_CreatePesantrenMastereducationlevel.php
> +        $this->forge->createTable('pstr_kelas', true);
apakah memang spesifik untuk kebutuhan pesantren sajakah ?

2022-10-13 22:18 UTC, pandigresik commented on app/Database/Migrations/2022-08-23-030018_CreatePelajaran.php
> +        $this->forge->addForeignKey('kelas_id', 'kelas', 'id');
ini reference ke tabel kelas, padahal diatas ada tabel pstr_kelas. ataukah memang seperti itu ?

2022-10-13 22:18 UTC, pandigresik commented on app/Database/Migrations/2022-08-23-033715_CreateGuru.php
> +            'pelajaran_id' => [
kalau dibuat seperti ini, maka asumsinya satu guru hanya bisa mengajar satu mata pelajaran saja. Apakah tidak dimungkinkan jika seorang guru mengajar lebih dari satu mata pelajaran ?

2022-10-13 22:18 UTC, pandigresik commented on app/Database/Migrations/2022-08-25-032708_CreateTingkatPendidikan.php
> +        $this->forge->createTable('tingkat_pendidikan', true);
bedanya apa dengan table pstr_educationlevel ?

2022-10-13 22:18 UTC, pandigresik commented on app/Database/Migrations/2022-08-25-033007_CreateKelas.php
>      }
apakah fungsi tabel ini berbeda dengan pstr_kelas ?

2022-10-13 22:18 UTC, pandigresik commented on app/Database/Migrations/2022-09-05-024354_CreateKalenderAkademik.php
> +    public function up()
bisa dihapus jika memang tidak digunakan

2022-10-13 22:18 UTC, pandigresik commented on app/Database/Migrations/2022-09-16-031303_CreateSiswa.php
> +            'birth_place' => [
kalau yang dimaksud ini adalah kota kelahiran, ada kemungkinan nama kota yang memiliki jumlah karakter > 15

2022-10-13 22:18 UTC, pandigresik commented on app/Database/Migrations/2022-09-16-031303_CreateSiswa.php
> +            'class_id' => [
jika class_id disini maka asumsinya adalah ini adalah kelas siswa kondisi sekarang, maka jika ada perpindahan kelas ( misalnya naik kelas ) maka nilai disini juga harus diubah juga. Konvensinya foreign_key menggunakan tablereference_id, jadi kelas_id bukan class_id karena reference ke table kelas

2022-10-13 22:18 UTC, pandigresik commented on app/Database/Migrations/2022-09-16-031303_CreateSiswa.php
> +        $this->forge->addUniqueKey('name');
ada kemungkinan siswa memiliki nama yang sama, jadi kurang tepat jika diberikan constraint unique di kolom name ini

2022-10-14 14:18 UTC, Muhammad-Ridho commented on app/Database/Migrations/2022-08-16-031332_CreatePesantrenMastereducationlevel.php
> +        $this->forge->createTable('pstr_educationlevel', true);
baik pak, akan saya perbaiki

2022-10-14 14:25 UTC, Muhammad-Ridho commented
baik pak, saya lupa ada beberapa penamaan yang tidak sama, akan segera saya perbaiki pak

2022-10-26 22:23 UTC, pandigresik requested changes
perubahan pada struktur table kemungkinan besar akan berimbas pada file yang berkaitan dengan CRUD dengan tabel tersebut. Setelah struktur tabel disesuaikan cek kembali file2 yang berkaitan

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-02-220243_CreateDonaturFund.php
> -<?php
ini yakin tabelnya sudah gak dipakai ? tabel ini gak ada hubungannya dengan pendaftaran. Kuatirnya ini tabel yang dibuat untuk modul lain

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-02-220243_CreateDonaturFund.php
> -
ini yakin tabelnya sudah gak dipakai ? tabel ini gak ada hubungannya dengan pendaftaran. Kuatirnya ini tabel yang dibuat untuk modul lain

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-02-220243_CreateDonaturFund.php
> -class CreateDonaturFund extends Migration
ini yakin tabelnya sudah gak dipakai ? tabel ini gak ada hubungannya dengan pendaftaran. Kuatirnya ini tabel yang dibuat untuk modul lain

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-02-220243_CreateDonaturFund.php
> -    {
ini yakin tabelnya sudah gak dipakai ? tabel ini gak ada hubungannya dengan pendaftaran. Kuatirnya ini tabel yang dibuat untuk modul lain

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-09-132413_CreateTugasTim.php
> -namespace App\Database\Migrations;
ini yakin tabelnya sudah gak dipakai ? tabel ini gak ada hubungannya dengan pendaftaran. Kuatirnya ini tabel yang dibuat untuk modul lain

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-09-132413_CreateTugasTim.php
> -        $this->forge->addField([
ini yakin tabelnya sudah gak dipakai ? tabel ini gak ada hubungannya dengan pendaftaran. Kuatirnya ini tabel yang dibuat untuk modul lain

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-09-132858_AddTugasTim.php
> -
ini yakin tabelnya sudah gak dipakai ? tabel ini gak ada hubungannya dengan pendaftaran. Kuatirnya ini tabel yang dibuat untuk modul lain

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-09-133705_CreateTimFund.php
> -namespace App\Database\Migrations;
ini yakin tabelnya sudah gak dipakai ? tabel ini gak ada hubungannya dengan pendaftaran. Kuatirnya ini tabel yang dibuat untuk modul lain

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-09-133912_AddTimFund.php
> -use CodeIgniter\Database\Migration;
ini yakin tabelnya sudah gak dipakai ? tabel ini gak ada hubungannya dengan pendaftaran. Kuatirnya ini tabel yang dibuat untuk modul lain

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-24-150908_CreatePeriode.php
> +        $this->forge->createTable('periode', true);
nama tabel periode ini akan membingungkan, ini periode apa ?

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-24-161445_CreatePendaftaran.php
> +            'class_id' => [
kelas_id  bukan class_id

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-24-161445_CreatePendaftaran.php
> +            'gender' => [
di tabel guru menggunakan jns_kelamin dengan tipe data char(1), disini menggunakan gender dengan tipe data varchar(20). Apakah tidak bisa diseragamkan ?

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-24-161741_CreateSiswa.php
> +            'gender' => [
di tabel guru menggunakan jns_kelamin dengan tipe data char(1), disini menggunakan gender dengan tipe data varchar(20). Apakah tidak bisa diseragamkan ?

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-24-161741_CreateSiswa.php
> +            'class_id' => [
kelas_id

2022-10-26 22:23 UTC, pandigresik commented on app/Database/Migrations/2022-10-24-161741_CreateSiswa.php
> +            'nis' => [
setau kami nis ini bisa saja diisi karakter . misalnya dan tidak ada operasi matematika yang menggunakan nis jadi lebih baik disimpan dalam tipe data varchar bukan int

2022-11-08 03:48 UTC, Muhammad-Ridho commented on app/Database/Migrations/2022-10-02-220243_CreateDonaturFund.php
> -<?php
mohon maaf pak untuk table donatur bukan punya saya, itu ada setelah saya pull di branch develope

2022-11-08 03:50 UTC, Muhammad-Ridho commented on app/Database/Migrations/2022-10-02-220243_CreateDonaturFund.php
> -
mohon maaf pak, untuk table tersebut bukan saya yang buat, itu ada setelah saya pull dari branch develope

2022-11-08 06:00 UTC, pandigresik commented on app/Database/Migrations/2022-10-02-220243_CreateDonaturFund.php
> -
mungkin lebih baik jangan dihapus, kuatirnya dipakai di module lain

2022-11-28 03:42 UTC, Muhammad-Ridho commented on app/Database/Migrations/2022-10-24-150908_CreatePeriode.php
> +        $this->forge->createTable('periode', true);
untuk table periode ini nantinya berisi semester ganjil dan genap pak

2022-12-01 07:10 UTC, pandigresik approved these changes

2022-12-01 07:10 UTC, merged